<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Foundations of Data Science I</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Foundations of Data Science I" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Foundations of Data Science I" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Jesse Lecy">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="operators.html">
<link rel="next" href="analysis-with-groups-in-r.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="custom.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science I</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a></li>
<li class="chapter" data-level="2" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>2</b> Introduction to R</a><ul>
<li class="chapter" data-level="2.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#navigation"><i class="fa fa-check"></i><b>2.1</b> Navigation</a><ul>
<li class="chapter" data-level="2.1.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#setting-your-working-directory"><i class="fa fa-check"></i><b>2.1.1</b> Setting Your Working Directory</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#commenting-code"><i class="fa fa-check"></i><b>2.2</b> Commenting Code</a></li>
<li class="chapter" data-level="2.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#help"><i class="fa fa-check"></i><b>2.3</b> Help</a></li>
<li class="chapter" data-level="2.4" data-path="introduction-to-r.html"><a href="introduction-to-r.html#install-programs-packages"><i class="fa fa-check"></i><b>2.4</b> Install Programs (packages)</a></li>
<li class="chapter" data-level="2.5" data-path="introduction-to-r.html"><a href="introduction-to-r.html#accessing-built-in-datasets-in-r"><i class="fa fa-check"></i><b>2.5</b> Accessing Built-In Datasets in R</a><ul>
<li class="chapter" data-level="2.5.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#basic-data-operations"><i class="fa fa-check"></i><b>2.5.1</b> Basic Data Operations</a></li>
<li class="chapter" data-level="2.5.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#using-the-lahman-data"><i class="fa fa-check"></i><b>2.5.2</b> Using the Lahman Data</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="introduction-to-r.html"><a href="introduction-to-r.html#master-table"><i class="fa fa-check"></i><b>2.6</b> <strong>MASTER TABLE</strong></a><ul>
<li class="chapter" data-level="2.6.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#example-analysis"><i class="fa fa-check"></i><b>2.6.1</b> Example Analysis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>3</b> Data Structures</a><ul>
<li class="chapter" data-level="3.1" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>3.1</b> Vectors</a></li>
<li class="chapter" data-level="3.2" data-path="data-structures.html"><a href="data-structures.html#casting"><i class="fa fa-check"></i><b>3.2</b> Casting</a></li>
<li class="chapter" data-level="3.3" data-path="data-structures.html"><a href="data-structures.html#the-combine-function"><i class="fa fa-check"></i><b>3.3</b> The Combine Function</a></li>
<li class="chapter" data-level="3.4" data-path="data-structures.html"><a href="data-structures.html#numeric-vectors"><i class="fa fa-check"></i><b>3.4</b> Numeric Vectors</a><ul>
<li class="chapter" data-level="3.4.1" data-path="data-structures.html"><a href="data-structures.html#integers-are-simple-numeric-vectors"><i class="fa fa-check"></i><b>3.4.1</b> Integers Are Simple Numeric Vectors</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="data-structures.html"><a href="data-structures.html#character-vectors"><i class="fa fa-check"></i><b>3.5</b> Character Vectors</a></li>
<li class="chapter" data-level="3.6" data-path="data-structures.html"><a href="data-structures.html#logical-vectors"><i class="fa fa-check"></i><b>3.6</b> Logical Vectors</a></li>
<li class="chapter" data-level="3.7" data-path="data-structures.html"><a href="data-structures.html#factors"><i class="fa fa-check"></i><b>3.7</b> Factors</a></li>
<li class="chapter" data-level="3.8" data-path="data-structures.html"><a href="data-structures.html#generating-vectors"><i class="fa fa-check"></i><b>3.8</b> Generating Vectors</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="operators.html"><a href="operators.html"><i class="fa fa-check"></i><b>4</b> Operators</a><ul>
<li class="chapter" data-level="4.1" data-path="operators.html"><a href="operators.html#datasets"><i class="fa fa-check"></i><b>4.1</b> Datasets</a><ul>
<li class="chapter" data-level="4.1.1" data-path="operators.html"><a href="operators.html#data-frames"><i class="fa fa-check"></i><b>4.1.1</b> Data Frames</a></li>
<li class="chapter" data-level="4.1.2" data-path="operators.html"><a href="operators.html#matrices"><i class="fa fa-check"></i><b>4.1.2</b> Matrices</a></li>
<li class="chapter" data-level="4.1.3" data-path="operators.html"><a href="operators.html#lists"><i class="fa fa-check"></i><b>4.1.3</b> Lists</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="operators.html"><a href="operators.html#subsets"><i class="fa fa-check"></i><b>4.2</b> Subsets</a></li>
<li class="chapter" data-level="4.3" data-path="operators.html"><a href="operators.html#variable-transformations"><i class="fa fa-check"></i><b>4.3</b> Variable Transformations</a></li>
<li class="chapter" data-level="4.4" data-path="operators.html"><a href="operators.html#missing-values-nas"><i class="fa fa-check"></i><b>4.4</b> Missing Values: NA’s</a></li>
<li class="chapter" data-level="4.5" data-path="operators.html"><a href="operators.html#the-attach-function"><i class="fa fa-check"></i><b>4.5</b> The ‘attach’ Function</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="merging-data.html"><a href="merging-data.html"><i class="fa fa-check"></i><b>5</b> Merging Data</a><ul>
<li class="chapter" data-level="5.1" data-path="merging-data.html"><a href="merging-data.html#packages-used-in-this-chapter"><i class="fa fa-check"></i><b>5.1</b> Packages Used in This Chapter</a></li>
<li class="chapter" data-level="5.2" data-path="merging-data.html"><a href="merging-data.html#relational-databases"><i class="fa fa-check"></i><b>5.2</b> Relational Databases</a></li>
<li class="chapter" data-level="5.3" data-path="merging-data.html"><a href="merging-data.html#set-theory"><i class="fa fa-check"></i><b>5.3</b> Set Theory</a><ul>
<li class="chapter" data-level="5.3.1" data-path="merging-data.html"><a href="merging-data.html#set-theory-functions"><i class="fa fa-check"></i><b>5.3.1</b> Set Theory Functions</a></li>
<li class="chapter" data-level="5.3.2" data-path="merging-data.html"><a href="merging-data.html#set-theory-using-logical-operators"><i class="fa fa-check"></i><b>5.3.2</b> Set Theory Using Logical Operators</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="merging-data.html"><a href="merging-data.html#merging-data-1"><i class="fa fa-check"></i><b>5.4</b> Merging Data</a><ul>
<li class="chapter" data-level="5.4.1" data-path="merging-data.html"><a href="merging-data.html#the-by.x-and-by.y-arguments"><i class="fa fa-check"></i><b>5.4.1</b> The by.x and by.y Arguments</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="merging-data.html"><a href="merging-data.html#non-unique-observations-in-id-variables"><i class="fa fa-check"></i><b>5.5</b> Non-Unique Observations in ID Variables</a><ul>
<li class="chapter" data-level="5.5.1" data-path="merging-data.html"><a href="merging-data.html#example-of-incorrect-merge"><i class="fa fa-check"></i><b>5.5.1</b> Example of Incorrect Merge</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="merging-data.html"><a href="merging-data.html#the-in-function"><i class="fa fa-check"></i><b>5.6</b> The %in% function</a></li>
<li class="chapter" data-level="5.7" data-path="merging-data.html"><a href="merging-data.html#the-match-function"><i class="fa fa-check"></i><b>5.7</b> The Match Function</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="analysis-with-groups-in-r.html"><a href="analysis-with-groups-in-r.html"><i class="fa fa-check"></i><b>6</b> Analysis with Groups in R</a><ul>
<li class="chapter" data-level="6.0.1" data-path="analysis-with-groups-in-r.html"><a href="analysis-with-groups-in-r.html#packages-used-in-this-chapter-1"><i class="fa fa-check"></i><b>6.0.1</b> Packages Used in this Chapter</a></li>
<li class="chapter" data-level="6.0.2" data-path="analysis-with-groups-in-r.html"><a href="analysis-with-groups-in-r.html#hypothetical-experimental-data"><i class="fa fa-check"></i><b>6.0.2</b> Hypothetical Experimental Data</a></li>
<li class="chapter" data-level="6.1" data-path="analysis-with-groups-in-r.html"><a href="analysis-with-groups-in-r.html#group-structure"><i class="fa fa-check"></i><b>6.1</b> Group Structure</a><ul>
<li class="chapter" data-level="6.1.1" data-path="analysis-with-groups-in-r.html"><a href="analysis-with-groups-in-r.html#what-are-groups"><i class="fa fa-check"></i><b>6.1.1</b> What Are Groups?</a></li>
<li class="chapter" data-level="6.1.2" data-path="analysis-with-groups-in-r.html"><a href="analysis-with-groups-in-r.html#main-take-away"><i class="fa fa-check"></i><b>6.1.2</b> Main Take-Away</a></li>
<li class="chapter" data-level="6.1.3" data-path="analysis-with-groups-in-r.html"><a href="analysis-with-groups-in-r.html#example"><i class="fa fa-check"></i><b>6.1.3</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="analysis-with-groups-in-r.html"><a href="analysis-with-groups-in-r.html#analysis-by-group"><i class="fa fa-check"></i><b>6.2</b> Analysis by Group</a><ul>
<li class="chapter" data-level="6.2.1" data-path="analysis-with-groups-in-r.html"><a href="analysis-with-groups-in-r.html#highest-ave-player-salary"><i class="fa fa-check"></i><b>6.2.1</b> Highest Ave Player Salary</a></li>
<li class="chapter" data-level="6.2.2" data-path="analysis-with-groups-in-r.html"><a href="analysis-with-groups-in-r.html#most-players-paid-over-5-million"><i class="fa fa-check"></i><b>6.2.2</b> Most Players Paid Over $5 Million</a></li>
<li class="chapter" data-level="6.2.3" data-path="analysis-with-groups-in-r.html"><a href="analysis-with-groups-in-r.html#fielding-positions"><i class="fa fa-check"></i><b>6.2.3</b> Fielding Positions</a></li>
<li class="chapter" data-level="6.2.4" data-path="analysis-with-groups-in-r.html"><a href="analysis-with-groups-in-r.html#country-of-birth"><i class="fa fa-check"></i><b>6.2.4</b> Country of Birth</a></li>
<li class="chapter" data-level="6.2.5" data-path="analysis-with-groups-in-r.html"><a href="analysis-with-groups-in-r.html#pay-raises"><i class="fa fa-check"></i><b>6.2.5</b> Pay Raises</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://webapp4.asu.edu/programs/t5/majorinfo/ASU00/PPPGEMS/graduate/false" target="blank">ASU</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Foundations of Data Science I</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="merging-data" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Merging Data</h1>
<div id="packages-used-in-this-chapter" class="section level2">
<h2><span class="header-section-number">5.1</span> Packages Used in This Chapter</h2>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb326-1" data-line-number="1"><span class="kw">library</span>( pander )</a>
<a class="sourceLine" id="cb326-2" data-line-number="2"><span class="kw">library</span>( dplyr )</a>
<a class="sourceLine" id="cb326-3" data-line-number="3"><span class="kw">library</span>( maps )</a></code></pre></div>
</div>
<div id="relational-databases" class="section level2">
<h2><span class="header-section-number">5.2</span> Relational Databases</h2>
<p>Modern databases are huge - think about the amount of information stored at Amazon in the history of each transation, the database where Google logs every single search from every person around the world, or Twitter’s database of all of the tweets (millions each day).</p>
<p>When databases become large, flat spreadsheet style formats are not useful because they create a lot of redundant information, are large to store, and are not efficient to search. Large datasets are instead stored in relational databases - sets of tables that contain unique IDs that allow them to be joined when necessary.</p>
<p>For example, consider a simple customer database. We don’t want to store customer info with our transactions because we would be repeating their name and street address every time they make a new purchase. As a result, we store customer information and transaction information separately.</p>
<table style="width:92%;">
<colgroup>
<col width="19%" />
<col width="18%" />
<col width="16%" />
<col width="22%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">CUSTOMER.ID</th>
<th align="center">FIRST.NAME</th>
<th align="center">LAST.NAME</th>
<th align="center">ADDRESS</th>
<th align="center">ZIP.CODE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">178</td>
<td align="center">Alvaro</td>
<td align="center">Jaurez</td>
<td align="center">123 Park Ave</td>
<td align="center">57701</td>
</tr>
<tr class="even">
<td align="center">934</td>
<td align="center">Janette</td>
<td align="center">Johnson</td>
<td align="center">456 Candy Ln</td>
<td align="center">57701</td>
</tr>
<tr class="odd">
<td align="center">269</td>
<td align="center">Latisha</td>
<td align="center">Shane</td>
<td align="center">1600 Penn Ave</td>
<td align="center">20500</td>
</tr>
</tbody>
</table>
<table style="width:47%;">
<colgroup>
<col width="19%" />
<col width="13%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">CUSTOMER.ID</th>
<th align="center">PRODUCT</th>
<th align="center">PRICE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">178</td>
<td align="center">video</td>
<td align="center">5.38</td>
</tr>
<tr class="even">
<td align="center">178</td>
<td align="center">shovel</td>
<td align="center">12</td>
</tr>
<tr class="odd">
<td align="center">269</td>
<td align="center">book</td>
<td align="center">3.99</td>
</tr>
<tr class="even">
<td align="center">269</td>
<td align="center">purse</td>
<td align="center">8</td>
</tr>
<tr class="odd">
<td align="center">934</td>
<td align="center">mirror</td>
<td align="center">7.64</td>
</tr>
</tbody>
</table>
<p>If we want to make the information actionable then we need to combine these datasets. For example, perhaps we want to know the average purchase amount from an individual in the 57701 zip code. We cannot answer that question with either dataset since the zip code is in one dataset, and the price is in another. We need to merge the data.</p>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb327-1" data-line-number="1"><span class="kw">merge</span>( customer.info, purchases )   </a></code></pre></div>
<pre><code>##   CUSTOMER.ID FIRST.NAME LAST.NAME       ADDRESS ZIP.CODE PRODUCT PRICE
## 1         178     Alvaro    Jaurez  123 Park Ave    57701   video  5.38
## 2         178     Alvaro    Jaurez  123 Park Ave    57701  shovel 12.00
## 3         269    Latisha     Shane 1600 Penn Ave    20500    book  3.99
## 4         269    Latisha     Shane 1600 Penn Ave    20500   purse  8.00
## 5         934    Janette   Johnson  456 Candy Ln    57701  mirror  7.64</code></pre>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb329-1" data-line-number="1">full.dat &lt;-<span class="st"> </span><span class="kw">merge</span>( customer.info, purchases ) </a>
<a class="sourceLine" id="cb329-2" data-line-number="2"></a>
<a class="sourceLine" id="cb329-3" data-line-number="3"><span class="kw">mean</span>( full.dat<span class="op">$</span>PRICE[ full.dat<span class="op">$</span>ZIP.CODE <span class="op">==</span><span class="st"> &quot;57701&quot;</span> ] )</a></code></pre></div>
<pre><code>## [1] 8.34</code></pre>
<p>In reality, each purchase would have a purchase ID that is linked to shipping addresses, customer complaints, seller ratings, etc. Each seller would have their own data table with info. Each purchase would be tied to a payment type, which has its own data table. The system gets quite complex, which is why it is important to pay attention to the details of putting the data back together again.</p>
<p><img src="figures/SampleRetailDatabase.png" /></p>
<p>We will cover a few details of data merges that will help you avoid common and very subtle mistakes that can lead to incorrect inferences.</p>
</div>
<div id="set-theory" class="section level2">
<h2><span class="header-section-number">5.3</span> Set Theory</h2>
<p>In order to merge data <strong>correctly</strong> you need to understand some very basic principles of set theory.</p>
<div id="set-theory-functions" class="section level3">
<h3><span class="header-section-number">5.3.1</span> Set Theory Functions</h3>
<p>Let’s assume we have two sets: set1=<em>[A,B]</em>, set2=<em>[B,C]</em>. Each element in this set represents a group of observations that occurs in the dataset. So B represents people that occur in both datasets, A represents people that occur only in the first dataset, and C represents people that only occur in the second dataset.</p>
<p>We can then describe membership through three operations:</p>
<table>
<thead>
<tr class="header">
<th>Operation</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>union</td>
<td>The universe of all elements across all both sets: [A,B,C]</td>
</tr>
<tr class="even">
<td>intersection</td>
<td>The elements shared by both sets: [B]</td>
</tr>
<tr class="odd">
<td>difference</td>
<td>The elements in my first set, not in my second [A] or [C]</td>
</tr>
</tbody>
</table>
<p>Let’s see how this might work in practice with an example of members of a study:</p>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb331-1" data-line-number="1">name &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;frank&quot;</span>,<span class="st">&quot;wanda&quot;</span>,<span class="st">&quot;sanjay&quot;</span>,<span class="st">&quot;nancy&quot;</span>)</a>
<a class="sourceLine" id="cb331-2" data-line-number="2">group &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;treat&quot;</span>,<span class="st">&quot;treat&quot;</span>,<span class="st">&quot;control&quot;</span>,<span class="st">&quot;control&quot;</span>)</a>
<a class="sourceLine" id="cb331-3" data-line-number="3">gender &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;male&quot;</span>,<span class="st">&quot;female&quot;</span>,<span class="st">&quot;male&quot;</span>,<span class="st">&quot;female&quot;</span>)</a>
<a class="sourceLine" id="cb331-4" data-line-number="4"></a>
<a class="sourceLine" id="cb331-5" data-line-number="5"><span class="kw">data.frame</span>( name, group, gender ) <span class="op">%&gt;%</span><span class="st"> </span>pander</a></code></pre></div>
<table style="width:40%;">
<colgroup>
<col width="12%" />
<col width="13%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">name</th>
<th align="center">group</th>
<th align="center">gender</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">frank</td>
<td align="center">treat</td>
<td align="center">male</td>
</tr>
<tr class="even">
<td align="center">wanda</td>
<td align="center">treat</td>
<td align="center">female</td>
</tr>
<tr class="odd">
<td align="center">sanjay</td>
<td align="center">control</td>
<td align="center">male</td>
</tr>
<tr class="even">
<td align="center">nancy</td>
<td align="center">control</td>
<td align="center">female</td>
</tr>
</tbody>
</table>
<p>For this example let’s define set 1 as the treatment group, and set 2 as all women in the study. Note that set membership is always defined as binary (you are in the set or out), but it can include multiple criteria (the set of animals can contains cats, dogs, and mice).</p>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb332-1" data-line-number="1">treated &lt;-<span class="st"> </span>name[ group <span class="op">==</span><span class="st"> &quot;treat&quot;</span> ]</a>
<a class="sourceLine" id="cb332-2" data-line-number="2"></a>
<a class="sourceLine" id="cb332-3" data-line-number="3">treated <span class="op">%&gt;%</span><span class="st"> </span>pander</a></code></pre></div>
<p><em>frank</em> and <em>wanda</em></p>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb333-1" data-line-number="1">females &lt;-<span class="st"> </span>name[ gender <span class="op">==</span><span class="st"> &quot;female&quot;</span> ]</a>
<a class="sourceLine" id="cb333-2" data-line-number="2"></a>
<a class="sourceLine" id="cb333-3" data-line-number="3">females <span class="op">%&gt;%</span><span class="st"> </span>pander</a></code></pre></div>
<p><em>wanda</em> and <em>nancy</em></p>
<p>Now we can specify group belonging using some convenient set theory functions: <strong>union()</strong>, <strong>setdiff()</strong>, and <strong>intersect()</strong>.</p>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb334-1" data-line-number="1"><span class="kw">union</span>( treated, females )</a></code></pre></div>
<pre><code>## [1] &quot;frank&quot; &quot;wanda&quot; &quot;nancy&quot;</code></pre>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb336-1" data-line-number="1"><span class="kw">intersect</span>( treated, females )</a></code></pre></div>
<pre><code>## [1] &quot;wanda&quot;</code></pre>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb338-1" data-line-number="1"><span class="kw">setdiff</span>( treated, females )</a></code></pre></div>
<pre><code>## [1] &quot;frank&quot;</code></pre>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb340-1" data-line-number="1"><span class="kw">setdiff</span>( females, treated )</a></code></pre></div>
<pre><code>## [1] &quot;nancy&quot;</code></pre>
<p>It is very important to note that <strong>union()</strong> and <strong>intersect()</strong> are symmetric functions, meaning <em>intersect(x,y)</em> will give you the same result as <em>intersect(y,x)</em>. The <strong>setdiff()</strong> function is not symmetric, however.</p>
</div>
<div id="set-theory-using-logical-operators" class="section level3">
<h3><span class="header-section-number">5.3.2</span> Set Theory Using Logical Operators</h3>
<p>Typically you will define your groups using logical operators, which perform the exact same funciton as set theory functions but are a little more expressive and flexible.</p>
<p>Let’s use the same example above where x=“treatment” and y=“female”, then consider these cases:</p>
<p><img src="figures/set_theory.png" /></p>
<p>Who belongs in each group?</p>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb342-1" data-line-number="1"><span class="co">#   x</span></a>
<a class="sourceLine" id="cb342-2" data-line-number="2"></a>
<a class="sourceLine" id="cb342-3" data-line-number="3">name[ group <span class="op">==</span><span class="st"> &quot;treat&quot;</span> ]</a></code></pre></div>
<pre><code>## [1] &quot;frank&quot; &quot;wanda&quot;</code></pre>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb344-1" data-line-number="1"><span class="co">#   x &amp; y</span></a>
<a class="sourceLine" id="cb344-2" data-line-number="2"></a>
<a class="sourceLine" id="cb344-3" data-line-number="3">name[ group <span class="op">==</span><span class="st"> &quot;treat&quot;</span> <span class="op">&amp;</span><span class="st"> </span>gender <span class="op">==</span><span class="st"> &quot;female&quot;</span> ]</a></code></pre></div>
<pre><code>## [1] &quot;wanda&quot;</code></pre>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb346-1" data-line-number="1"><span class="co">#   x &amp; ! y</span></a>
<a class="sourceLine" id="cb346-2" data-line-number="2"></a>
<a class="sourceLine" id="cb346-3" data-line-number="3">name[ group <span class="op">==</span><span class="st"> &quot;treat&quot;</span> <span class="op">&amp;</span><span class="st"> </span>gender <span class="op">!=</span><span class="st"> &quot;female&quot;</span> ]</a></code></pre></div>
<pre><code>## [1] &quot;frank&quot;</code></pre>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb348-1" data-line-number="1"><span class="co">#  x | y</span></a>
<a class="sourceLine" id="cb348-2" data-line-number="2"></a>
<a class="sourceLine" id="cb348-3" data-line-number="3">name[ group <span class="op">==</span><span class="st"> &quot;treat&quot;</span> <span class="op">|</span><span class="st"> </span>gender <span class="op">==</span><span class="st"> &quot;female&quot;</span> ]</a></code></pre></div>
<pre><code>## [1] &quot;frank&quot; &quot;wanda&quot; &quot;nancy&quot;</code></pre>
<p>Who belongs in these groups?</p>
<ul>
<li>!x &amp; !y</li>
<li>x &amp; ! ( x &amp; y )</li>
<li>( x | y ) &amp; ! ( x &amp; y )</li>
</ul>
</div>
</div>
<div id="merging-data-1" class="section level2">
<h2><span class="header-section-number">5.4</span> Merging Data</h2>
<p><strong>The Merge Function</strong></p>
<p>The merge function joins two datasets. The function requires two datasets as the arguments, and they need to share a unique ID variable. Recall the example from above:</p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb350-1" data-line-number="1"><span class="kw">merge</span>( customer.info, purchases )</a></code></pre></div>
<pre><code>##   CUSTOMER.ID FIRST.NAME LAST.NAME       ADDRESS ZIP.CODE PRODUCT PRICE
## 1         178     Alvaro    Jaurez  123 Park Ave    57701   video  5.38
## 2         178     Alvaro    Jaurez  123 Park Ave    57701  shovel 12.00
## 3         269    Latisha     Shane 1600 Penn Ave    20500    book  3.99
## 4         269    Latisha     Shane 1600 Penn Ave    20500   purse  8.00
## 5         934    Janette   Johnson  456 Candy Ln    57701  mirror  7.64</code></pre>
<p>The important thing to keep in mind is that the default merge operation uses the <strong>intersection</strong> of the two datasets. It will drop all elements that don’t occur in both datasets. We may want to fine-tune this as to not lose valuable data and potentially bias our analysis. As an example, no illegal immigrants will have social security numbers, so if you are merging using the SSN, you will drop this group from the data, which could impact your results.</p>
<p><img src="figures/xy.png" /></p>
<p>With a little help from the set theory examples above, we can think about which portions of the data we wish to drop and which portions we wish to keep.</p>
<table>
<thead>
<tr class="header">
<th>Argument</th>
<th>Usage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>all=F</td>
<td>DEFAULT - new dataset contains intersection of X and Y (B only)</td>
</tr>
<tr class="even">
<td>all=T</td>
<td>New dataset contains union of X and Y (A, B &amp; C)</td>
</tr>
<tr class="odd">
<td>all.x=T</td>
<td>New dataset contains A and B, not C</td>
</tr>
<tr class="even">
<td>all.y=T</td>
<td>New dataset contains B and C, not A</td>
</tr>
</tbody>
</table>
<p>Here is some demonstrations with examples adapted from the R help file.</p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb352-1" data-line-number="1">authors   </a></code></pre></div>
<pre><code>##       surname nationality deceased
## 1       Tukey          US      yes
## 2     Tierney          US       no
## 3      Ripley          UK       no
## 4      McNeil   Australia       no
## 5 Shakespeare     England      yes</code></pre>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb354-1" data-line-number="1">books    </a></code></pre></div>
<pre><code>##          name                     title
## 1       Tukey Exploratory Data Analysis
## 2    Venables Modern Applied Statistics
## 3      Ripley        Spatial Statistics
## 4      Ripley     Stochastic Simulation
## 5      McNeil Interactive Data Analysis
## 6 R Core Team      An Introduction to R</code></pre>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb356-1" data-line-number="1"><span class="co"># adding books to the author bios dataset  ( set B only )</span></a>
<a class="sourceLine" id="cb356-2" data-line-number="2"></a>
<a class="sourceLine" id="cb356-3" data-line-number="3"><span class="kw">merge</span>(authors, books, <span class="dt">by.x =</span> <span class="st">&quot;surname&quot;</span>, <span class="dt">by.y =</span> <span class="st">&quot;name&quot;</span>)    </a></code></pre></div>
<pre><code>##   surname nationality deceased                     title
## 1  McNeil   Australia       no Interactive Data Analysis
## 2  Ripley          UK       no        Spatial Statistics
## 3  Ripley          UK       no     Stochastic Simulation
## 4   Tukey          US      yes Exploratory Data Analysis</code></pre>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb358-1" data-line-number="1"><span class="co"># adding author bios to the books dataset  ( set B only )</span></a>
<a class="sourceLine" id="cb358-2" data-line-number="2"></a>
<a class="sourceLine" id="cb358-3" data-line-number="3"><span class="kw">merge</span>(books, authors, <span class="dt">by.x =</span> <span class="st">&quot;name&quot;</span>, <span class="dt">by.y =</span> <span class="st">&quot;surname&quot;</span>)    </a></code></pre></div>
<pre><code>##     name                     title nationality deceased
## 1 McNeil Interactive Data Analysis   Australia       no
## 2 Ripley        Spatial Statistics          UK       no
## 3 Ripley     Stochastic Simulation          UK       no
## 4  Tukey Exploratory Data Analysis          US      yes</code></pre>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb360-1" data-line-number="1"><span class="co"># keep books without author bios, lose authors without books  ( sets A and B )</span></a>
<a class="sourceLine" id="cb360-2" data-line-number="2"></a>
<a class="sourceLine" id="cb360-3" data-line-number="3"><span class="kw">merge</span>( books, authors, <span class="dt">by.x =</span> <span class="st">&quot;name&quot;</span>, <span class="dt">by.y =</span> <span class="st">&quot;surname&quot;</span>, <span class="dt">all.x=</span>T )     </a></code></pre></div>
<pre><code>##          name                     title nationality deceased
## 1      McNeil Interactive Data Analysis   Australia       no
## 2 R Core Team      An Introduction to R        &lt;NA&gt;     &lt;NA&gt;
## 3      Ripley        Spatial Statistics          UK       no
## 4      Ripley     Stochastic Simulation          UK       no
## 5       Tukey Exploratory Data Analysis          US      yes
## 6    Venables Modern Applied Statistics        &lt;NA&gt;     &lt;NA&gt;</code></pre>
<div class="sourceCode" id="cb362"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb362-1" data-line-number="1"><span class="co"># keep authors without book listed, lose books without author bios   ( sets B and C )</span></a>
<a class="sourceLine" id="cb362-2" data-line-number="2"></a>
<a class="sourceLine" id="cb362-3" data-line-number="3"><span class="kw">merge</span>( books, authors, <span class="dt">by.x =</span> <span class="st">&quot;name&quot;</span>, <span class="dt">by.y =</span> <span class="st">&quot;surname&quot;</span>, <span class="dt">all.y=</span>T )    </a></code></pre></div>
<pre><code>##          name                     title nationality deceased
## 1      McNeil Interactive Data Analysis   Australia       no
## 2      Ripley        Spatial Statistics          UK       no
## 3      Ripley     Stochastic Simulation          UK       no
## 4 Shakespeare                      &lt;NA&gt;     England      yes
## 5     Tierney                      &lt;NA&gt;          US       no
## 6       Tukey Exploratory Data Analysis          US      yes</code></pre>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb364-1" data-line-number="1"><span class="co"># dont&#39; throw out any data   ( sets A and B and C )</span></a>
<a class="sourceLine" id="cb364-2" data-line-number="2"></a>
<a class="sourceLine" id="cb364-3" data-line-number="3"><span class="kw">merge</span>( books, authors, <span class="dt">by.x =</span> <span class="st">&quot;name&quot;</span>, <span class="dt">by.y =</span> <span class="st">&quot;surname&quot;</span>, <span class="dt">all=</span>T )   </a></code></pre></div>
<pre><code>##          name                     title nationality deceased
## 1      McNeil Interactive Data Analysis   Australia       no
## 2 R Core Team      An Introduction to R        &lt;NA&gt;     &lt;NA&gt;
## 3      Ripley        Spatial Statistics          UK       no
## 4      Ripley     Stochastic Simulation          UK       no
## 5 Shakespeare                      &lt;NA&gt;     England      yes
## 6     Tierney                      &lt;NA&gt;          US       no
## 7       Tukey Exploratory Data Analysis          US      yes
## 8    Venables Modern Applied Statistics        &lt;NA&gt;     &lt;NA&gt;</code></pre>
<p>Also note that the order of your datasets in the argument list will impact the inclusion or exclusion of elements.</p>
<p>merge( x, y, all=F ) EQUALS merge( y, x, all=F )</p>
<p>merge( x, y, all.x=T ) DOES NOT EQUAL merge( y, x, all.x=T )</p>
<div id="the-by.x-and-by.y-arguments" class="section level3">
<h3><span class="header-section-number">5.4.1</span> The by.x and by.y Arguments</h3>
<p>When you use the default <strong>merge()</strong> function without specifying the variables to merge upon, the function will check for common variable names across the two datasets. If there are multiple, it will join the shared variables to create a new unique key. This might be problematic if that was not the intent.</p>
<p>Take the example of combining fielding and salary data in the Lahman package. If we are not explicit about the merge variable, we may get odd results. Note that they two datasets share four ID variables.</p>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb366-1" data-line-number="1"><span class="kw">library</span>( Lahman )</a>
<a class="sourceLine" id="cb366-2" data-line-number="2"><span class="kw">data</span>( Fielding )</a>
<a class="sourceLine" id="cb366-3" data-line-number="3"><span class="kw">data</span>( Salaries )</a></code></pre></div>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb367-1" data-line-number="1"><span class="kw">intersect</span>( <span class="kw">names</span>(Fielding), <span class="kw">names</span>(Salaries) )</a></code></pre></div>
<pre><code>## [1] &quot;playerID&quot; &quot;yearID&quot;   &quot;teamID&quot;   &quot;lgID&quot;</code></pre>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb369-1" data-line-number="1"><span class="co"># merge id</span></a>
<a class="sourceLine" id="cb369-2" data-line-number="2"></a>
<a class="sourceLine" id="cb369-3" data-line-number="3">int &lt;-<span class="st"> </span><span class="kw">intersect</span>( <span class="kw">names</span>(Fielding), <span class="kw">names</span>(Salaries) )</a>
<a class="sourceLine" id="cb369-4" data-line-number="4"></a>
<a class="sourceLine" id="cb369-5" data-line-number="5"><span class="kw">paste</span>( int[<span class="dv">1</span>],int[<span class="dv">2</span>],int[<span class="dv">3</span>],int[<span class="dv">4</span>], <span class="dt">sep=</span><span class="st">&quot;.&quot;</span> )</a></code></pre></div>
<pre><code>## [1] &quot;playerID.yearID.teamID.lgID&quot;</code></pre>
<p>To avoid problems, be explicit using the <em>by.x</em> and <em>by.x</em> arguments to control which variable is used for the merge.</p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb371-1" data-line-number="1"><span class="kw">head</span>( <span class="kw">merge</span>( Salaries, Fielding ) )</a></code></pre></div>
<pre><code>##   yearID teamID lgID  playerID salary stint POS  G GS InnOuts  PO  A E DP
## 1   1985    ATL   NL barkele01 870000     1   P 20 18     221   2  9 1  0
## 2   1985    ATL   NL bedrost01 550000     1   P 37 37     620  13 23 4  3
## 3   1985    ATL   NL benedbr01 545000     1   C 70 67    1698 314 35 4  1
## 4   1985    ATL   NL  campri01 633333     1   P 66  2     383   7 13 4  3
## 5   1985    ATL   NL ceronri01 625000     1   C 91 76    2097 384 48 6  4
## 6   1985    ATL   NL chambch01 800000     1  1B 39 27     814 299 25 1 31
##   PB WP SB CS ZR
## 1 NA NA NA NA NA
## 2 NA NA NA NA NA
## 3  1  9 65 24  1
## 4 NA NA NA NA NA
## 5  6 20 69 29  1
## 6 NA NA NA NA NA</code></pre>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb373-1" data-line-number="1"><span class="kw">head</span>( <span class="kw">merge</span>( Salaries, Fielding, <span class="dt">by.x=</span><span class="st">&quot;playerID&quot;</span>, <span class="dt">by.y=</span><span class="st">&quot;playerID&quot;</span> ) )</a></code></pre></div>
<pre><code>##    playerID yearID.x teamID.x lgID.x  salary yearID.y stint teamID.y
## 1 aardsda01     2010      SEA     AL 2750000     2009     1      SEA
## 2 aardsda01     2010      SEA     AL 2750000     2015     1      ATL
## 3 aardsda01     2010      SEA     AL 2750000     2006     1      CHN
## 4 aardsda01     2010      SEA     AL 2750000     2008     1      BOS
## 5 aardsda01     2010      SEA     AL 2750000     2013     1      NYN
## 6 aardsda01     2010      SEA     AL 2750000     2012     1      NYA
##   lgID.y POS  G GS InnOuts PO A E DP PB WP SB CS ZR
## 1     AL   P 73  0     214  2 5 0  1 NA NA NA NA NA
## 2     NL   P 33  0      92  0 1 1  0 NA NA NA NA NA
## 3     NL   P 45  0     159  1 5 0  1 NA NA NA NA NA
## 4     AL   P 47  0     146  3 6 0  0 NA NA NA NA NA
## 5     NL   P 43  0     119  1 5 0  0 NA NA NA NA NA
## 6     AL   P  1  0       3  0 0 0  0 NA NA NA NA NA</code></pre>
</div>
</div>
<div id="non-unique-observations-in-id-variables" class="section level2">
<h2><span class="header-section-number">5.5</span> Non-Unique Observations in ID Variables</h2>
<p>In some rare instances, you will need to merge to datasets that have non-singular elements in the unique key ID variables, meaning each observation / individual appears more than one time in the data. Note that in this case, for each occurance of an observation / individual in your X dataset, you will merge once with each occurance of the same observation / individual in the Y dataset. The result will be a multiplicative expansion of the size of your dataset.</p>
<p>For example, if John appears on four separate rows of X, and three seperate rows of Y, the new dataset will contain 12 rows of John (4 x 3 = 12).</p>
<p>dataset X contains four separate instances of an individual [ X1, X2, X3, X4 ]</p>
<p>dataset Y contains three separate instances of an individual [ Y1, Y2, Y3 ]</p>
<p>After the merge we have one row for each pair:</p>
<p>X1-Y1<br />
X1-Y2<br />
X1-Y3<br />
X2-Y1<br />
X2-Y2<br />
X2-Y3<br />
X3-Y1<br />
X3-Y2<br />
X3-Y3<br />
X4-Y1<br />
X4-Y2<br />
X4-Y3</p>
<p>For example, perhaps a sales company has a database that keeps track of biographical data, and sales performance. Perhaps we want to see if there is peak age for sales performance. We need to merge these datasets.</p>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb375-1" data-line-number="1">bio &lt;-<span class="st"> </span><span class="kw">data.frame</span>( <span class="dt">name=</span><span class="kw">c</span>(<span class="st">&quot;John&quot;</span>,<span class="st">&quot;John&quot;</span>,<span class="st">&quot;John&quot;</span>),</a>
<a class="sourceLine" id="cb375-2" data-line-number="2">                   <span class="dt">year=</span><span class="kw">c</span>(<span class="dv">2000</span>,<span class="dv">2001</span>,<span class="dv">2002</span>),</a>
<a class="sourceLine" id="cb375-3" data-line-number="3">                   <span class="dt">age=</span><span class="kw">c</span>(<span class="dv">43</span>,<span class="dv">44</span>,<span class="dv">45</span>) )</a>
<a class="sourceLine" id="cb375-4" data-line-number="4"></a>
<a class="sourceLine" id="cb375-5" data-line-number="5">performance &lt;-<span class="st"> </span><span class="kw">data.frame</span>( <span class="dt">name=</span><span class="kw">c</span>(<span class="st">&quot;John&quot;</span>,<span class="st">&quot;John&quot;</span>,<span class="st">&quot;John&quot;</span>),</a>
<a class="sourceLine" id="cb375-6" data-line-number="6">                           <span class="dt">year=</span><span class="kw">c</span>(<span class="dv">2000</span>,<span class="dv">2001</span>,<span class="dv">2002</span>),</a>
<a class="sourceLine" id="cb375-7" data-line-number="7">                           <span class="dt">sales=</span><span class="kw">c</span>(<span class="st">&quot;15k&quot;</span>,<span class="st">&quot;20k&quot;</span>,<span class="st">&quot;17k&quot;</span>) )</a>
<a class="sourceLine" id="cb375-8" data-line-number="8"></a>
<a class="sourceLine" id="cb375-9" data-line-number="9"><span class="co"># correct merge</span></a>
<a class="sourceLine" id="cb375-10" data-line-number="10"></a>
<a class="sourceLine" id="cb375-11" data-line-number="11"><span class="kw">merge</span>( bio, performance, <span class="dt">by.x=</span><span class="kw">c</span>(<span class="st">&quot;name&quot;</span>,<span class="st">&quot;year&quot;</span>), <span class="dt">by.y=</span><span class="kw">c</span>(<span class="st">&quot;name&quot;</span>,<span class="st">&quot;year&quot;</span>) ) </a></code></pre></div>
<pre><code>##   name year age sales
## 1 John 2000  43   15k
## 2 John 2001  44   20k
## 3 John 2002  45   17k</code></pre>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb377-1" data-line-number="1"><span class="co"># incorrect merge</span></a>
<a class="sourceLine" id="cb377-2" data-line-number="2"></a>
<a class="sourceLine" id="cb377-3" data-line-number="3"><span class="kw">merge</span>( bio, performance, <span class="dt">by.x=</span><span class="kw">c</span>(<span class="st">&quot;name&quot;</span>), <span class="dt">by.y=</span><span class="kw">c</span>(<span class="st">&quot;name&quot;</span>) )  </a></code></pre></div>
<pre><code>##   name year.x age year.y sales
## 1 John   2000  43   2000   15k
## 2 John   2000  43   2001   20k
## 3 John   2000  43   2002   17k
## 4 John   2001  44   2000   15k
## 5 John   2001  44   2001   20k
## 6 John   2001  44   2002   17k
## 7 John   2002  45   2000   15k
## 8 John   2002  45   2001   20k
## 9 John   2002  45   2002   17k</code></pre>
<p><strong>It is good practice to check the size (number of rows) of your dataset before and after a merge. If it has expanded, chances are you either used the wrong unique IDs, or your dataset contains duplicates.</strong></p>
<div id="example-of-incorrect-merge" class="section level3">
<h3><span class="header-section-number">5.5.1</span> Example of Incorrect Merge</h3>
<p>Here is a tangible example using the Lahman baseball dataset. Perhaps we want to examine the relationship between fielding position and salary. The <em>Fielding</em> dataset contains fielding position information, and the <em>Salaries</em> dataset contains salary information. We can merge these two datasets using the <em>playerID</em> field.</p>
<p>If we are not thoughtful about this, however, we will end up causing problems. Let’s look at an example using Kirby Pucket.</p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb379-1" data-line-number="1">kirby.fielding &lt;-<span class="st"> </span>Fielding[ Fielding<span class="op">$</span>playerID <span class="op">==</span><span class="st"> &quot;puckeki01&quot;</span> , ]</a>
<a class="sourceLine" id="cb379-2" data-line-number="2"></a>
<a class="sourceLine" id="cb379-3" data-line-number="3"><span class="kw">head</span>( kirby.fielding )</a></code></pre></div>
<pre><code>##        playerID yearID stint teamID lgID POS   G  GS InnOuts  PO  A E DP
## 83848 puckeki01   1984     1    MIN   AL  OF 128 128    3377 438 16 3  4
## 85157 puckeki01   1985     1    MIN   AL  OF 161 160    4213 465 19 8  5
## 86489 puckeki01   1986     1    MIN   AL  OF 160 157    4155 429  8 6  3
## 87896 puckeki01   1987     1    MIN   AL  OF 147 147    3820 341  8 5  2
## 89264 puckeki01   1988     1    MIN   AL  OF 158 157    4049 450 12 3  4
## 90685 puckeki01   1989     1    MIN   AL  OF 157 154    3985 438 13 4  3
##       PB WP SB CS ZR
## 83848 NA NA NA NA NA
## 85157 NA NA NA NA NA
## 86489 NA NA NA NA NA
## 87896 NA NA NA NA NA
## 89264 NA NA NA NA NA
## 90685 NA NA NA NA NA</code></pre>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb381-1" data-line-number="1"><span class="kw">nrow</span>( kirby.fielding )</a></code></pre></div>
<pre><code>## [1] 21</code></pre>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb383-1" data-line-number="1">kirby.salary &lt;-<span class="st"> </span>Salaries[ Salaries<span class="op">$</span>playerID <span class="op">==</span><span class="st"> &quot;puckeki01&quot;</span> , ]</a>
<a class="sourceLine" id="cb383-2" data-line-number="2"></a>
<a class="sourceLine" id="cb383-3" data-line-number="3"><span class="kw">head</span>( kirby.salary )</a></code></pre></div>
<pre><code>##      yearID teamID lgID  playerID  salary
## 280    1985    MIN   AL puckeki01  130000
## 917    1986    MIN   AL puckeki01  255000
## 1610   1987    MIN   AL puckeki01  465000
## 2244   1988    MIN   AL puckeki01 1090000
## 2922   1989    MIN   AL puckeki01 2000000
## 3717   1990    MIN   AL puckeki01 2816667</code></pre>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb385-1" data-line-number="1"><span class="kw">nrow</span>( kirby.salary )</a></code></pre></div>
<pre><code>## [1] 13</code></pre>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb387-1" data-line-number="1">kirby.field.salary &lt;-<span class="st"> </span><span class="kw">merge</span>( kirby.fielding, kirby.salary, <span class="dt">by.x=</span><span class="st">&quot;playerID&quot;</span>, <span class="dt">by.y=</span><span class="st">&quot;playerID&quot;</span> )</a>
<a class="sourceLine" id="cb387-2" data-line-number="2"></a>
<a class="sourceLine" id="cb387-3" data-line-number="3"><span class="kw">head</span>( <span class="kw">select</span>( kirby.field.salary, yearID.x, yearID.y,   POS,    G,  GS, salary ) )</a></code></pre></div>
<pre><code>##   yearID.x yearID.y POS   G  GS  salary
## 1     1984     1985  OF 128 128  130000
## 2     1984     1986  OF 128 128  255000
## 3     1984     1987  OF 128 128  465000
## 4     1984     1988  OF 128 128 1090000
## 5     1984     1989  OF 128 128 2000000
## 6     1984     1990  OF 128 128 2816667</code></pre>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb389-1" data-line-number="1"><span class="kw">nrow</span>( kirby.field.salary )</a></code></pre></div>
<pre><code>## [1] 273</code></pre>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb391-1" data-line-number="1"><span class="dv">21</span><span class="op">*</span><span class="dv">13</span></a></code></pre></div>
<pre><code>## [1] 273</code></pre>
<p>What we have done here is taken each year of fielding data, and matched it to <strong>every</strong> year of salary data. We can see that we have 21 fielding observations and 13 years of salary data, so our resulting dataset is 273 observation pairs.</p>
<p>This merge also makes it difficult to answer the question of the relationship between fielding position and salary if players change positions over time.</p>
<p>The correct merge in this case would be a merge on a playerID-yearID pair. We can create a unique key by combining playerID and yearID using <strong>paste()</strong>:</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb393-1" data-line-number="1"><span class="kw">head</span>( <span class="kw">paste</span>( kirby.fielding<span class="op">$</span>playerID, kirby.fielding<span class="op">$</span>yearID, <span class="dt">sep=</span><span class="st">&quot;.&quot;</span>) )</a></code></pre></div>
<pre><code>## [1] &quot;puckeki01.1984&quot; &quot;puckeki01.1985&quot; &quot;puckeki01.1986&quot; &quot;puckeki01.1987&quot;
## [5] &quot;puckeki01.1988&quot; &quot;puckeki01.1989&quot;</code></pre>
<p>But there is a simple solution as the merge function also allows for multiple variables to be used for a <strong>merge()</strong> command.</p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb395-1" data-line-number="1">kirby.field.salary &lt;-<span class="st"> </span><span class="kw">merge</span>( kirby.fielding, kirby.salary, </a>
<a class="sourceLine" id="cb395-2" data-line-number="2">                            <span class="dt">by.x=</span><span class="kw">c</span>(<span class="st">&quot;playerID&quot;</span>,<span class="st">&quot;yearID&quot;</span>), </a>
<a class="sourceLine" id="cb395-3" data-line-number="3">                            <span class="dt">by.y=</span><span class="kw">c</span>(<span class="st">&quot;playerID&quot;</span>,<span class="st">&quot;yearID&quot;</span>)   )</a>
<a class="sourceLine" id="cb395-4" data-line-number="4"></a>
<a class="sourceLine" id="cb395-5" data-line-number="5"><span class="kw">nrow</span>( kirby.field.salary )</a></code></pre></div>
<pre><code>## [1] 20</code></pre>
</div>
</div>
<div id="the-in-function" class="section level2">
<h2><span class="header-section-number">5.6</span> The %in% function</h2>
<p>Since we are talking about intersections and matches, I want to briefly introduce the <strong>%in%</strong> function. It is a combination of the two.</p>
<p>The <strong>intersect()</strong> function returns a list of unique matches between two vectors.</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb397-1" data-line-number="1"><span class="kw">data</span>(Salaries)</a>
<a class="sourceLine" id="cb397-2" data-line-number="2"><span class="kw">data</span>(Fielding)</a>
<a class="sourceLine" id="cb397-3" data-line-number="3"><span class="kw">intersect</span>( <span class="kw">names</span>(Salaries), <span class="kw">names</span>(Fielding) )</a></code></pre></div>
<pre><code>## [1] &quot;yearID&quot;   &quot;teamID&quot;   &quot;lgID&quot;     &quot;playerID&quot;</code></pre>
<p>The <strong>match()</strong> function returns the position of matched elements.</p>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb399-1" data-line-number="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;C&quot;</span>,<span class="st">&quot;B&quot;</span>)</a>
<a class="sourceLine" id="cb399-2" data-line-number="2"></a>
<a class="sourceLine" id="cb399-3" data-line-number="3">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;B&quot;</span>,<span class="st">&quot;D&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;F&quot;</span>)</a>
<a class="sourceLine" id="cb399-4" data-line-number="4"></a>
<a class="sourceLine" id="cb399-5" data-line-number="5"><span class="kw">match</span>( x, y )</a></code></pre></div>
<pre><code>## [1]  3  1 NA  1</code></pre>
<p>The <strong>%in%</strong> function returns a logical vector, where TRUE signifies that the element in <em>y</em> also occurs in <em>x</em>. In other words, does a specific element in <em>y</em> belong to the intersection of <em>x</em>,<em>y</em>.</p>
<p>This is very useful for creating subsets of data that belong to both sets.</p>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb401-1" data-line-number="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;C&quot;</span>)</a>
<a class="sourceLine" id="cb401-2" data-line-number="2"></a>
<a class="sourceLine" id="cb401-3" data-line-number="3">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;B&quot;</span>,<span class="st">&quot;D&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;F&quot;</span>,<span class="st">&quot;B&quot;</span>)</a>
<a class="sourceLine" id="cb401-4" data-line-number="4"></a>
<a class="sourceLine" id="cb401-5" data-line-number="5">y <span class="op">%in%</span><span class="st"> </span>x <span class="co"># does each element of y occur anywhere in x?</span></a></code></pre></div>
<pre><code>## [1]  TRUE FALSE  TRUE  TRUE FALSE  TRUE</code></pre>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb403-1" data-line-number="1">y[ y <span class="op">%in%</span><span class="st"> </span>x] <span class="co"># keep only data that occurs in both</span></a></code></pre></div>
<pre><code>## [1] &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;B&quot;</code></pre>
</div>
<div id="the-match-function" class="section level2">
<h2><span class="header-section-number">5.7</span> The Match Function</h2>
<p>Often times we do not need to merge data, we may just need sort data in one dataset so that it matches the order of another dataset. This is accomplished using the <strong>match()</strong> function.</p>
<p>Note that we can rearrange the order of a dataset by referencing the desired position.</p>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb405-1" data-line-number="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Second&quot;</span>,<span class="st">&quot;Third&quot;</span>,<span class="st">&quot;First&quot;</span>)</a>
<a class="sourceLine" id="cb405-2" data-line-number="2"></a>
<a class="sourceLine" id="cb405-3" data-line-number="3">x</a></code></pre></div>
<pre><code>## [1] &quot;Second&quot; &quot;Third&quot;  &quot;First&quot;</code></pre>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb407-1" data-line-number="1">x[ <span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">2</span>) ]</a></code></pre></div>
<pre><code>## [1] &quot;First&quot;  &quot;Second&quot; &quot;Third&quot;</code></pre>
<p>The <strong>match()</strong> function returns the <em>positions</em> of matches of its <em>first</em> vector to the <em>second</em> vector listed in the arguments. Or in other words, the <em>order</em> that vector 2 would need to follow to match vector 1.</p>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb409-1" data-line-number="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;C&quot;</span>)</a>
<a class="sourceLine" id="cb409-2" data-line-number="2"></a>
<a class="sourceLine" id="cb409-3" data-line-number="3">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;B&quot;</span>,<span class="st">&quot;D&quot;</span>,<span class="st">&quot;A&quot;</span>)</a>
<a class="sourceLine" id="cb409-4" data-line-number="4"></a>
<a class="sourceLine" id="cb409-5" data-line-number="5"><span class="kw">cbind</span>( x, y )</a></code></pre></div>
<pre><code>##      x   y  
## [1,] &quot;A&quot; &quot;B&quot;
## [2,] &quot;B&quot; &quot;D&quot;
## [3,] &quot;C&quot; &quot;A&quot;</code></pre>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb411-1" data-line-number="1"><span class="kw">match</span>( x, y )</a></code></pre></div>
<pre><code>## [1]  3  1 NA</code></pre>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb413-1" data-line-number="1"><span class="kw">match</span>( y, x) <span class="co"># not a symmetric operation!</span></a></code></pre></div>
<pre><code>## [1]  2 NA  1</code></pre>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb415-1" data-line-number="1"><span class="co"># In the y vector:</span></a>
<a class="sourceLine" id="cb415-2" data-line-number="2"><span class="co">#</span></a>
<a class="sourceLine" id="cb415-3" data-line-number="3"><span class="co">#  [3]=A</span></a>
<a class="sourceLine" id="cb415-4" data-line-number="4"><span class="co">#  [1]=B</span></a>
<a class="sourceLine" id="cb415-5" data-line-number="5"><span class="co"># [NA]=D (no match)</span></a>
<a class="sourceLine" id="cb415-6" data-line-number="6"></a>
<a class="sourceLine" id="cb415-7" data-line-number="7">order.y &lt;-<span class="st"> </span><span class="kw">match</span>( x, y )</a>
<a class="sourceLine" id="cb415-8" data-line-number="8"></a>
<a class="sourceLine" id="cb415-9" data-line-number="9">y[ order.y ]</a></code></pre></div>
<pre><code>## [1] &quot;A&quot; &quot;B&quot; NA</code></pre>
<p>We can see that <strong>match()</strong> returns the correct order to put <em>y</em> in so that it matches the order of <em>x</em>. In the re-ordered vector, the first element is the original third element <em>A</em>, the second element is the original first element <em>B</em>, and there is no third element because <em>D</em> did not match anything in <em>x</em>.</p>
<p>Note the order of arguments in the function:</p>
<blockquote>
<p>match( data I want to match to , data I need to re-order )</p>
</blockquote>
<p>We can use this position information to re-order <em>y</em> as follows:</p>
<div class="sourceCode" id="cb417"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb417-1" data-line-number="1">x &lt;-<span class="st"> </span><span class="kw">sample</span>( LETTERS[<span class="dv">1</span><span class="op">:</span><span class="dv">15</span>], <span class="dt">size=</span><span class="dv">10</span> )</a>
<a class="sourceLine" id="cb417-2" data-line-number="2"></a>
<a class="sourceLine" id="cb417-3" data-line-number="3">y &lt;-<span class="st"> </span><span class="kw">sample</span>( LETTERS[<span class="dv">1</span><span class="op">:</span><span class="dv">15</span>], <span class="dt">size=</span><span class="dv">10</span> )</a>
<a class="sourceLine" id="cb417-4" data-line-number="4"></a>
<a class="sourceLine" id="cb417-5" data-line-number="5"><span class="kw">cbind</span>( x, y )</a></code></pre></div>
<pre><code>##       x   y  
##  [1,] &quot;O&quot; &quot;J&quot;
##  [2,] &quot;B&quot; &quot;C&quot;
##  [3,] &quot;C&quot; &quot;H&quot;
##  [4,] &quot;M&quot; &quot;O&quot;
##  [5,] &quot;H&quot; &quot;D&quot;
##  [6,] &quot;G&quot; &quot;K&quot;
##  [7,] &quot;J&quot; &quot;I&quot;
##  [8,] &quot;A&quot; &quot;B&quot;
##  [9,] &quot;E&quot; &quot;A&quot;
## [10,] &quot;L&quot; &quot;G&quot;</code></pre>
<div class="sourceCode" id="cb419"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb419-1" data-line-number="1">order.y &lt;-<span class="st"> </span><span class="kw">match</span>( x, y )</a>
<a class="sourceLine" id="cb419-2" data-line-number="2"></a>
<a class="sourceLine" id="cb419-3" data-line-number="3">y.new &lt;-<span class="st"> </span>y[ order.y ]</a>
<a class="sourceLine" id="cb419-4" data-line-number="4"></a>
<a class="sourceLine" id="cb419-5" data-line-number="5"><span class="kw">cbind</span>( x, y.new )</a></code></pre></div>
<pre><code>##       x   y.new
##  [1,] &quot;O&quot; &quot;O&quot;  
##  [2,] &quot;B&quot; &quot;B&quot;  
##  [3,] &quot;C&quot; &quot;C&quot;  
##  [4,] &quot;M&quot; NA   
##  [5,] &quot;H&quot; &quot;H&quot;  
##  [6,] &quot;G&quot; &quot;G&quot;  
##  [7,] &quot;J&quot; &quot;J&quot;  
##  [8,] &quot;A&quot; &quot;A&quot;  
##  [9,] &quot;E&quot; NA   
## [10,] &quot;L&quot; NA</code></pre>
<div class="sourceCode" id="cb421"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb421-1" data-line-number="1"><span class="co"># Note the result if you confuse the order or arguments</span></a>
<a class="sourceLine" id="cb421-2" data-line-number="2"></a>
<a class="sourceLine" id="cb421-3" data-line-number="3">order.y &lt;-<span class="st"> </span><span class="kw">match</span>( y, x )</a>
<a class="sourceLine" id="cb421-4" data-line-number="4"></a>
<a class="sourceLine" id="cb421-5" data-line-number="5">y.new &lt;-<span class="st"> </span>y[ order.y ]</a>
<a class="sourceLine" id="cb421-6" data-line-number="6"></a>
<a class="sourceLine" id="cb421-7" data-line-number="7"><span class="kw">cbind</span>( x, y.new )</a></code></pre></div>
<pre><code>##       x   y.new
##  [1,] &quot;O&quot; &quot;I&quot;  
##  [2,] &quot;B&quot; &quot;H&quot;  
##  [3,] &quot;C&quot; &quot;D&quot;  
##  [4,] &quot;M&quot; &quot;J&quot;  
##  [5,] &quot;H&quot; NA   
##  [6,] &quot;G&quot; NA   
##  [7,] &quot;J&quot; NA   
##  [8,] &quot;A&quot; &quot;C&quot;  
##  [9,] &quot;E&quot; &quot;B&quot;  
## [10,] &quot;L&quot; &quot;K&quot;</code></pre>
<p>This comes in handy when we are matching information between two tables. For example, in GIS the map regions follow a specific order but your data does not. Create a color scheme for levels of your data, and then re-order the colors so they match the correct region on the map. In this example, we will look at unemployment levels by county.</p>
<div class="sourceCode" id="cb423"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb423-1" data-line-number="1"><span class="kw">library</span>( maps )</a>
<a class="sourceLine" id="cb423-2" data-line-number="2"><span class="kw">data</span>( county.fips )</a>
<a class="sourceLine" id="cb423-3" data-line-number="3"><span class="kw">data</span>( unemp )</a>
<a class="sourceLine" id="cb423-4" data-line-number="4"></a>
<a class="sourceLine" id="cb423-5" data-line-number="5"><span class="kw">map</span>( <span class="dt">database=</span><span class="st">&quot;county&quot;</span> )</a></code></pre></div>
<p><img src="DS4PS-I_files/figure-html/unnamed-chunk-92-1.png" width="768" /></p>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb424-1" data-line-number="1"><span class="co"># assign a color to each level of unemployment, red = high, gray = medium, blue = low</span></a>
<a class="sourceLine" id="cb424-2" data-line-number="2"></a>
<a class="sourceLine" id="cb424-3" data-line-number="3">color.function &lt;-<span class="st"> </span><span class="kw">colorRampPalette</span>( <span class="kw">c</span>(<span class="st">&quot;steelblue&quot;</span>, <span class="st">&quot;gray70&quot;</span>, <span class="st">&quot;firebrick&quot;</span>) )</a>
<a class="sourceLine" id="cb424-4" data-line-number="4"></a>
<a class="sourceLine" id="cb424-5" data-line-number="5"></a>
<a class="sourceLine" id="cb424-6" data-line-number="6">color.vector &lt;-<span class="st"> </span><span class="kw">cut</span>( <span class="kw">rank</span>(unemp<span class="op">$</span>unemp), <span class="dt">breaks=</span><span class="dv">7</span>, <span class="dt">labels=</span><span class="kw">color.function</span>( <span class="dv">7</span> ) )</a>
<a class="sourceLine" id="cb424-7" data-line-number="7"></a>
<a class="sourceLine" id="cb424-8" data-line-number="8">color.vector &lt;-<span class="st"> </span><span class="kw">as.character</span>( color.vector )</a>
<a class="sourceLine" id="cb424-9" data-line-number="9"></a>
<a class="sourceLine" id="cb424-10" data-line-number="10"><span class="kw">head</span>( color.vector )</a></code></pre></div>
<pre><code>## [1] &quot;#B28282&quot; &quot;#B28282&quot; &quot;#B22222&quot; &quot;#B25252&quot; &quot;#B28282&quot; &quot;#B22222&quot;</code></pre>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb426-1" data-line-number="1"><span class="co"># doesn&#39;t look quite right</span></a>
<a class="sourceLine" id="cb426-2" data-line-number="2"></a>
<a class="sourceLine" id="cb426-3" data-line-number="3"><span class="kw">map</span>( <span class="dt">database=</span><span class="st">&quot;county&quot;</span>, <span class="dt">col=</span>color.vector, <span class="dt">fill=</span>T, <span class="dt">lty=</span><span class="dv">0</span> )</a></code></pre></div>
<p><img src="DS4PS-I_files/figure-html/unnamed-chunk-92-2.png" width="768" /></p>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb427-1" data-line-number="1"><span class="co"># what went wrong here? </span></a>
<a class="sourceLine" id="cb427-2" data-line-number="2"></a>
<a class="sourceLine" id="cb427-3" data-line-number="3"><span class="co"># our unemployment data (and thus the color vector) follows a different order</span></a>
<a class="sourceLine" id="cb427-4" data-line-number="4"></a>
<a class="sourceLine" id="cb427-5" data-line-number="5"><span class="kw">cbind</span>( <span class="dt">map.id=</span>county.fips<span class="op">$</span>fips, <span class="dt">data.id=</span>unemp<span class="op">$</span>fips, color.vector )[ <span class="dv">2500</span><span class="op">:</span><span class="dv">2510</span> , ]</a></code></pre></div>
<pre><code>##       map.id  data.id color.vector
##  [1,] &quot;48011&quot; &quot;47149&quot; &quot;#B28282&quot;   
##  [2,] &quot;48013&quot; &quot;47151&quot; &quot;#B22222&quot;   
##  [3,] &quot;48015&quot; &quot;47153&quot; &quot;#B22222&quot;   
##  [4,] &quot;48017&quot; &quot;47155&quot; &quot;#B28282&quot;   
##  [5,] &quot;48019&quot; &quot;47157&quot; &quot;#B28282&quot;   
##  [6,] &quot;48021&quot; &quot;47159&quot; &quot;#B22222&quot;   
##  [7,] &quot;48023&quot; &quot;47161&quot; &quot;#B25252&quot;   
##  [8,] &quot;48025&quot; &quot;47163&quot; &quot;#B3B3B3&quot;   
##  [9,] &quot;48027&quot; &quot;47165&quot; &quot;#B28282&quot;   
## [10,] &quot;48029&quot; &quot;47167&quot; &quot;#B25252&quot;   
## [11,] &quot;48031&quot; &quot;47169&quot; &quot;#B25252&quot;</code></pre>
<div class="sourceCode" id="cb429"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb429-1" data-line-number="1"><span class="co"># place the color vector in the correct order</span></a>
<a class="sourceLine" id="cb429-2" data-line-number="2"></a>
<a class="sourceLine" id="cb429-3" data-line-number="3">this.order &lt;-<span class="st"> </span><span class="kw">match</span>( county.fips<span class="op">$</span>fips, unemp<span class="op">$</span>fips )</a>
<a class="sourceLine" id="cb429-4" data-line-number="4"></a>
<a class="sourceLine" id="cb429-5" data-line-number="5">color.vec.ordered &lt;-<span class="st"> </span>color.vector[ this.order ]</a>
<a class="sourceLine" id="cb429-6" data-line-number="6"></a>
<a class="sourceLine" id="cb429-7" data-line-number="7"><span class="co"># colors now match their correct counties</span></a>
<a class="sourceLine" id="cb429-8" data-line-number="8"></a>
<a class="sourceLine" id="cb429-9" data-line-number="9"><span class="kw">map</span>( <span class="dt">database=</span><span class="st">&quot;county&quot;</span>, <span class="dt">col=</span>color.vec.ordered, <span class="dt">fill=</span>T, <span class="dt">lty=</span><span class="dv">0</span> )</a>
<a class="sourceLine" id="cb429-10" data-line-number="10"><span class="kw">title</span>( <span class="dt">main=</span><span class="st">&quot;Unemployment Levels by County in 2009&quot;</span>)</a></code></pre></div>
<p><img src="DS4PS-I_files/figure-html/unnamed-chunk-92-3.png" width="768" /></p>
<p>Note that elements can be recycled from your <em>y</em> vector:</p>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb430-1" data-line-number="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;C&quot;</span>,<span class="st">&quot;B&quot;</span>)</a>
<a class="sourceLine" id="cb430-2" data-line-number="2"></a>
<a class="sourceLine" id="cb430-3" data-line-number="3">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;B&quot;</span>,<span class="st">&quot;D&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;F&quot;</span>)</a>
<a class="sourceLine" id="cb430-4" data-line-number="4"></a>
<a class="sourceLine" id="cb430-5" data-line-number="5"><span class="kw">cbind</span>( x, y )</a></code></pre></div>
<pre><code>##      x   y  
## [1,] &quot;A&quot; &quot;B&quot;
## [2,] &quot;B&quot; &quot;D&quot;
## [3,] &quot;C&quot; &quot;A&quot;
## [4,] &quot;B&quot; &quot;F&quot;</code></pre>
<div class="sourceCode" id="cb432"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb432-1" data-line-number="1"><span class="kw">match</span>( x, y )</a></code></pre></div>
<pre><code>## [1]  3  1 NA  1</code></pre>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb434-1" data-line-number="1">order.y &lt;-<span class="st"> </span><span class="kw">match</span>( x, y )</a>
<a class="sourceLine" id="cb434-2" data-line-number="2"></a>
<a class="sourceLine" id="cb434-3" data-line-number="3">y.new &lt;-<span class="st"> </span>y[ order.y ]</a>
<a class="sourceLine" id="cb434-4" data-line-number="4"></a>
<a class="sourceLine" id="cb434-5" data-line-number="5"><span class="kw">cbind</span>( x, y.new )</a></code></pre></div>
<pre><code>##      x   y.new
## [1,] &quot;A&quot; &quot;A&quot;  
## [2,] &quot;B&quot; &quot;B&quot;  
## [3,] &quot;C&quot; NA   
## [4,] &quot;B&quot; &quot;B&quot;</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="operators.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="analysis-with-groups-in-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/Unit-03-Merging-Data.Rmd",
"text": "Edit"
},
"download": ["DS4PS-I.pdf", "DS4PS-I.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
